//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.Data
{
    using System.Collections.ObjectModel;

    public partial class Condition
    {
        public Condition()
        {
            Equipments = new ObservableCollection<Equipment>();
        }

        public int ID { get; set; }
        public string Description { get; set; }
        public virtual ObservableCollection<Equipment> Equipments { get; set; }
    }
}
